<div class="alert alert-success" role="alert">
<h1>Clase #1 </h1>
<h2>Computación</h2>
<h2>Física, UNAM </h2>
<h3>Ollin Demian Langle Chimal</h3>
<p>ollin.langle@ciencias.unam.mx</p>
</div>

<div class="alert alert-info" role="alert">
<p class ="lead"> 
<h1>Parte 1: Introducción a Jupyter Notebooks </h1>
<p> En esta sección vamos a revisar la utilidad y la distribución de los Notebooks de Jupyter </p>
</div>

# ¿Qué es un notebook?
### Es un *cuaderno* que se guarda en un tipo de archivo llamado _**JSON**_ con la particularidad de que mediante el paquete **Jupyter** (antes IPython) de Python podemos tener una interfaz gráfica en un navegador que nos permite ejecutar código de diversos lenguajes de programación además de documentación escrita en el formato de texto *Markdown*.

### Esto hace que los notebooks sean leíbles tanto por computadoras como por humanos. 

# ¿Qué es una celda?

### Cada espacio que podemos editar es llamada _celda_, en ellas podemos ingresar texto plano y configurarla para ser código que se ejecuta o texto simple.

### Las celdas se componen de una entrada que es lo que escribimos y una salida que es el resultado que obtenemos

#### Ejemplo:

In [13]:
2+2

4

# ¿Qué es un kernel?

### Además de la interfaz gráfica con la que  contamos en el navegador, Jupyter cuenta con un motor computacional que ejecuta el código que escribimos en el notebook.

### Existen kernel para distintos lenguajes de programación (el original es el de IPython)
### Dentro de ellos destacan:
* IPython (Python)
* IRkernel (R)
* IJulia

Los cuales son mantenidos por el equipo de Jupyter, pero al ser software libre y abierto existen una gran cantidad de kernels desarrollados por la comunidad.

* Go
* Fortran
* Spark
* Octave
* Matlab
* Mathematica

<div class="alert alert-info" role="alert">
<p class ="lead"> 
<h1>Parte 1: Introducción a Markdown </h1>
<p> En esta sección vamos a ver un poco de sintaxis de Markdown </p>
</div>

# ¿Por qué Markdown?

# Aaron Swartz
![Aaron](http://pixel.nymag.com/imgs/daily/intelligencer/2013/01/14/14-aaron-swartz.w710.h473.2x.jpg)

# Para encabezados utilizamos el signo **#** (hash/she) antes de la línea
### Existen diferentes tipos de encabezados (headers)

# H1
```
# H1
```
## H2
```
## H2
```
### H3
```
### H3
```
#### H4
```
#### H4
```
##### H5
```
##### H5
```

# También podemos utilizar (Whatsapp anyone?):
**NEGRITAS**
```
**NEGRITAS**
```
_CURSIVA_
```
*CURSIVA*
```
**_AMBAS_**
```
**_AMBAS_**
```
~~TACHADO~~
```
~~TACHADO~~
```

# $\LaTeX$ mode o _math_ mode

# $\beta = \alpha + \frac{e^{n}}{n}$
```
$ \beta = \alpha + \frac{e^{n}}{n}$
```

# Listas ordenadas
### Podemos utilizar puntos numéricos:
1. Punto número uno
1. Punto número dos
1. Punto número tres
1. Punto número cuatro
1. Punto número cinco

```
1. Punto número uno
1. Punto número dos
1. Punto número tres
1. Punto número cuatro
1. Punto número cinco
```

### Enlistado regular con cualquiera de estos símbolos:
* Punto 1
+ Punto 2
- Punto 3

```
* Punto 1
+ Punto 2
- Punto 3
```
### Anidado

* Punto 1
    * Punto 1.1
        * Punto 1.1.1
        * Punto 1.1.2
    * Punto 1.2
        * Punto 1.2.1
        * Punto 1.2.2
* Punto 2

```
* Punto 1
    * Punto 1.1
        * Punto 1.1.1
        * Punto 1.1.2
    * Punto 1.2
        * Punto 1.2.1
        * Punto 1.2.2
* Punto 2
```

# Hipervínculos o links

[La página del profe Ollin](https://www.ollinlangle.com)
```
[La página del profe Ollin](https://www.ollinlangle.com)
```

Las URLs se convierten automáticamente si las escribimos entre `< >` por ejemplo <http://www.ollinlangle.com>


# Imágenes como la Aaron Swartz las podemos poner con una sintaxis muy parecida a la de los hipervínculos, sólo tenemos que escaparla con `!` (bang)

`![Aaron](http://pixel.nymag.com/imgs/daily/intelligencer/2013/01/14/14-aaron-swartz.w710.h473.2x.jpg)`

# Código
### A veces queremos poner código que no se ejecuta, para eso podemos utilizar Markdown y tendremos las propiedades de resaltado
Si queremos decir en la misma línea que estamos escribiendo que algo es una instrucción a la computadora podemos utilizar 
el código escapado con acento grave `bash`.
También podemos utilizar bloques de código en diferentes lenguajes:
### Python
```python
import numpy as np
for i in np.arange(10):
    print(i)
```

### Julia
```julia
using Gadfly
for i ∈ 1:10
    println(i)
end
```

### R
```R
library(ggplot2)
for(i in 1:10){
print(i)
}
```

# Tablas


| Las tablas        | son muy           | importantes  |
| :------------- |:-------------:| -----:|
|  Los puntos     | significan | la alineación |
|1|2|3|
|4|5|6|
|7|8|9|

```
| Las tablas        | son muy           | importantes  |
| :------------- |:-------------:| -----:|
|  Los puntos     | significan | la alineación |
|1|2|3|
```


# Citar
Podemos hacer _citas_ mediate el uso del signo `>`
> Information is power. But like all power, there are those who want to keep it for themselves. The world’s entire scientific and cultural heritage, published over centuries in books and journals, is increasingly being digitized and locked up by a handful of private corporations. Want to read the papers featuring the most famous results of the sciences? You’ll need to send enormous amounts to publishers like Reed Elsevier. __*Aaron Swartz*__

# También podemos usar separadores para ordenar mejor nuestras ideas
## Estos los podemos generar con tres o más de:
* `*`
* `-`
* `_`

Entonces podemos escribir una idea
***
Hacer separación para escribir otra
___
Definir algunas cosas

---
O simplemente para que se vea bonito y sea más fácil de leer

```

Entonces podemos escribir una idea
***
Hacer separación para escribir otra
___
Definir algunas cosas

---
O simplemente para que se vea bonito y sea más fácil de leer
```
##  <font size="5" color="red">¡Cuidado!</font>  si usamos underscores podemos hacer que lo de arriba se vuelva un encabezado (hay que usar espacios)

![julia](https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Julia_prog_language.svg/1200px-Julia_prog_language.svg.png)

# ¿Quién es Julia?
Julia es un lenguaje de programación orientado al cómputo científico, tiene la particularidad de ser un lenguaje dinámico
por lo que podemos interactuar con él mediante un **REPL** (Read, Evaluate, Print, Loop). Otros lenguajes de este tipo son Python, R, Ruby, Coffee, Lua, etc. La particularidad de este (ahora ya hay formas de hacerlo con algunos otros) es que no es un lenguaje _interpretado_ sino que es compilado!

# ¿Por qué usar julia?

[![Why Julia](http://img.youtube.com/vi/x0lI4omOYTw/0.jpg)](http://www.youtube.com/watch?v=x0lI4omOYTw)

# ¡Elimina el problema de los dos lenguajes!
### Combina la facilidad de programación de lenguajes interpretados como Python, Matlab y Lua con la velocidad de ejecución de los lenguajes compilados como C, Fortran, Java y Go. Esto gracias a que está construido sobre la Low Level Virtual Machine (LLVM) que le permite compilar su código siendo un lenguaje dinámico además de tener un gran detector de tipos. Esto hace que Julia pueda ser rápido en tiempo de programador y tiempo de ejecución.

![LLVM](https://llvm.org/img/LLVM-Logo-Derivative-4.png)

<div class="alert alert-info" role="alert">
<p class ="lead"> 
<h1>Parte 3: Introducción a Julia </h1>
<p> En esta sección vamos a comenzar lo importante, pensar y programar </p>
</div>

# Variables
Podemos asignar variables de la siguiente manera:
```
x = 10
```
Por el hecho de soportar UTF-8 las variables pueden ser las mismas letras y símbolos que utilizamos en libros y cuadernos

$\tau = I \alpha$

#### Ejemplo:

In [1]:
α = 10
β = 20
γ = α + β

γ

30

In [3]:
γ

30

In [ ]:
Α Γ

Podemos cambiar el valor de una variable ya definida

In [6]:
α = β * 3

60

In [7]:
α

60

Como podemos observar, estamos usando enteros pero también existen otros tipos de variables

In [4]:
typeof(α*1.0)

Float64

¿Notan el tipo entero y el 64? ¿qué significa? ¿Qué otros tipos existen?

In [6]:
typeof(1.0)

Float64

¿Float? ¿Ya hicieron su tarea de sistemas de punto flotante? ¿Qué significa?

In [7]:
typeof("¡Hola mundo!")

String

In [8]:
typeof('a')

Char

Char de caracter y String de cadena (cuerda) de caracteres

In [9]:
saludo = "¡Hola mundo!"

"¡Hola mundo!"

In [10]:
saludo

"¡Hola mundo!"

In [5]:
α

10

In [11]:
greeting = "Hello world!"

"Hello world!"

# Operaciones

In [12]:
α, β

(60,20)

In [13]:
α + β, 
α - β, 
α * β, 
α / β, 
α % β

(80,40,1200,3.0,0)

In [8]:
10 % 5

0

In [9]:
10 % 3

1

In [14]:
α += 1
α

61

In [ ]:
a = a * 2

In [11]:
α += 1
α

60

In [12]:
α *= 2
α

120

In [13]:
α /= 2
α

60.0

In [14]:
β

20

In [18]:
α == β

false

In [19]:
α != β

true

In [20]:
α ≠ β

true

In [21]:
α <= β

false

In [22]:
α >= β

true

In [23]:
prueba = 8.2

8.2

In [24]:
round(prueba), ceil(prueba), floor(prueba), trunc(prueba)

(8.0,9.0,8.0,8.0)

In [25]:
prueba = 8.6

8.6

In [26]:
round(prueba), ceil(prueba), floor(prueba), trunc(prueba)

(9.0,9.0,8.0,8.0)

In [27]:
prueba = -2

-2

In [28]:
abs(prueba)

2

In [29]:
abs2(prueba)

4

In [30]:
sqrt(prueba)

LoadError: DomainError:
sqrt will only return a complex result if called with a complex argument. Try sqrt(complex(x)).

In [31]:
sqrt(complex(prueba))

0.0 + 1.4142135623730951im

In [32]:
sqrt(abs(prueba))

1.4142135623730951

In [33]:
log(α), log(10,α), log10(α), log2(α)

(4.0943445622221,1.7781512503836434,1.7781512503836436,5.906890595608519)

In [34]:
sin(α), cos(α), tan(α), tanh(α)

(-0.3048106211022167,-0.9524129804151563,0.320040389379563,1.0)

## Números imaginarios y complejos

utilizamos `im` para indicar que es la parte imaginaria

In [35]:
2 + 5im

2 + 5im

In [36]:
complejo = 2+5im

2 + 5im

In [37]:
complejo^2

-21 + 20im

## Números racionales

In [39]:
6//9

2//3

In [14]:
typeof(15//5)

Rational{Int64}

In [41]:
float(6//9)

0.6666666666666666

In [42]:
(6//9)*5

10//3

In [43]:
(6//9)*5.

3.333333333333333

# Arreglos

Algo escencial en el cómputo científico es el uso de vectores, en el caso de Julia estos se manejan como arreglos los cuales se extienden en distintas dimensiones para generar matrices, arreglos de arreglos, tensores, etc.

In [22]:
a = [1,2,3,4,5,6,7,8,9]

9-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [45]:
eltype(a)

Int64

In [17]:
typeof(a)

Array{Int64,1}

In [23]:
b = [1,2,3,4,5,6,7,8,9.]

9-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
 7.0
 8.0
 9.0

In [20]:
eltype(b)

Any

In [48]:
length(a), ndims(a), size(a)

(9,1,(9,))

In [49]:
zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [50]:
zeros(2,3)

2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [51]:
zeros(2,3,4)

2×3×4 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0
 0.0  0.0  0.0

In [52]:
ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [53]:
rand(4,4)

4×4 Array{Float64,2}:
 0.117779  0.863607  0.20101   0.0164602
 0.763872  0.341166  0.601239  0.523333 
 0.237089  0.944658  0.60302   0.51354  
 0.698658  0.327066  0.315478  0.153834 

In [54]:
eye(4)

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [55]:
vcat(a,b)

18-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
 7.0
 8.0
 9.0
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
 7.0
 8.0
 9.0

In [56]:
hcat(a,b)

9×2 Array{Float64,2}:
 1.0  1.0
 2.0  2.0
 3.0  3.0
 4.0  4.0
 5.0  5.0
 6.0  6.0
 7.0  7.0
 8.0  8.0
 9.0  9.0

In [57]:
a + b

9-element Array{Float64,1}:
  2.0
  4.0
  6.0
  8.0
 10.0
 12.0
 14.0
 16.0
 18.0

In [21]:
a

LoadError: UndefVarError: a not defined

In [59]:
a'

1×9 Array{Int64,2}:
 1  2  3  4  5  6  7  8  9

In [24]:
a * b

LoadError: DimensionMismatch("Cannot multiply two vectors")

In [28]:
c = a * b'

9×9 Array{Float64,2}:
 1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0
 2.0   4.0   6.0   8.0  10.0  12.0  14.0  16.0  18.0
 3.0   6.0   9.0  12.0  15.0  18.0  21.0  24.0  27.0
 4.0   8.0  12.0  16.0  20.0  24.0  28.0  32.0  36.0
 5.0  10.0  15.0  20.0  25.0  30.0  35.0  40.0  45.0
 6.0  12.0  18.0  24.0  30.0  36.0  42.0  48.0  54.0
 7.0  14.0  21.0  28.0  35.0  42.0  49.0  56.0  63.0
 8.0  16.0  24.0  32.0  40.0  48.0  56.0  64.0  72.0
 9.0  18.0  27.0  36.0  45.0  54.0  63.0  72.0  81.0

In [62]:
a' * b

1-element Array{Float64,1}:
 285.0

In [63]:
a .* b

9-element Array{Float64,1}:
  1.0
  4.0
  9.0
 16.0
 25.0
 36.0
 49.0
 64.0
 81.0

In [64]:
a[1]

1

In [65]:
a[end]

9

In [26]:
typeof(1:4)

UnitRange{Int64}

In [66]:
a[3:end]

7-element Array{Int64,1}:
 3
 4
 5
 6
 7
 8
 9

In [27]:
c

LoadError: UndefVarError: c not defined

In [67]:
c[1,1]

1.0

In [30]:
c[1][2]

LoadError: BoundsError

In [29]:
c[2,5]

10.0

Podemos cambiar los valores de las entradas

In [70]:
a

9-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [71]:
a[3] = 1
a

9-element Array{Int64,1}:
 1
 2
 1
 4
 5
 6
 7
 8
 9

In [72]:
a[4:9] = 0
a

9-element Array{Int64,1}:
 1
 2
 1
 0
 0
 0
 0
 0
 0

# Strings

In [73]:
'α'

'α'

In [31]:
α

60.0

In [32]:
Int('α')

945

In [75]:
α

60.0

In [76]:
Char(110)

'n'

In [77]:
saludo

"¡Hola mundo!"

In [78]:
saludo[1]

'¡'

In [79]:
saludo * greeting

"¡Hola mundo!Hello world!"

Los valores de la variable dentro de un String

In [80]:
"Muchas veces queremos escribir algo y poner el valor de una variable. Podemos por ejemplo decir que α = 60 pero en muchas ocasiones no sabemos el valor actual de dicha variable, por lo que es conveniente tener una manera de introducirla. Esto se logra con el signo de pesos \$. Por ejemplo α = $α"

"Muchas veces queremos escribir algo y poner el valor de una variable. Podemos por ejemplo decir que α = 60 pero en muchas ocasiones no sabemos el valor actual de dicha variable, por lo que es conveniente tener una manera de introducirla. Esto se logra con el signo de pesos \$. Por ejemplo α = 60.0"

In [38]:
a = 0
a = ["hola", "adios","casa"]
for i ∈ a
    # a += 1
    #println("Hola esta es la iteración $a")
    println(i)
    
end

hola
adios
casa


## Esto nos lleva a los ciclos for (for loops)
Son una expresión que significa repetir una acción mientras se cumpla la condición asignada
por ejemplo:
```
a = 0
for i ∈ 1:5
    a += 1
    println("Hola esta es la iteración $a")
end
```
Significa que por cada número en el intervalo 1:5 se repitan las acciones que se encuentran adentro de dicho `for`
es decir, i va a tomar el valor `1`, a se va a actualizar a 0+1=1 y se va a imprimir a pantalla el mensaje "Hola esta es la iteración 'valor de a'".
Esto se va a repetir para i = 2, i = 3, i = 4 e i = 5. Después de esto terminará el ciclo pues i = 6 no entra en la petición.

Notamos que usamos la notación de dos números separados por `:` para definirlo como un intervalo, por default caminará en pasos de 1 pero esto lo podemos modificar.

In [82]:
for i ∈ 1:2
    println(i)
end

1
2


In [83]:
for i ∈ 1:0.5:2
    println(i)
end

1.0
1.5
2.0


In [84]:
for i ∈ -1:0.5:2
    println(i)
end

-1.0
-0.5
0.0
0.5
1.0
1.5
2.0


In [1]:
for i ∈ -1:0.5:-2
    println(i)
end

In [86]:
for i ∈ -1:-0.5:-2
    println(i)
end

-1.0
-1.5
-2.0


Un intervalo lo podemos volver arreglo con la función `collect`

In [2]:
collect(1:0.2:10)

46-element Array{Float64,1}:
  1.0
  1.2
  1.4
  1.6
  1.8
  2.0
  2.2
  2.4
  2.6
  2.8
  3.0
  3.2
  3.4
  ⋮  
  7.8
  8.0
  8.2
  8.4
  8.6
  8.8
  9.0
  9.2
  9.4
  9.6
  9.8
 10.0

También nos sirve para recorrer un arreglo

In [88]:
a = [1,2,3,4,5,6,7,8,9]

9-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [89]:
for elemento ∈ a
    println(elemento)
end

1
2
3
4
5
6
7
8
9


In [90]:
for indice ∈ 1:length(a)
    println(a[indice])
end

1
2
3
4
5
6
7
8
9


In [91]:
for indice ∈ eachindex(a)
    println(a[indice])
end

1
2
3
4
5
6
7
8
9


# Condicionales

Muchas veces queremos que algo se ejecute únicamente si se cumple una condición en específico, para eso utilizamos los condicionales `if`

In [92]:
for i in 1:100
    if i%13 == 0
        println("$i es múltiplo de 13")
    end
end

13 es múltiplo de 13
26 es múltiplo de 13
39 es múltiplo de 13
52 es múltiplo de 13
65 es múltiplo de 13
78 es múltiplo de 13
91 es múltiplo de 13


In [93]:
for i in 1:100
    if i%2 != 0
        println("$i no es múltiplo de 2")
    end
end

1 no es múltiplo de 2
3 no es múltiplo de 2
5 no es múltiplo de 2
7 no es múltiplo de 2
9 no es múltiplo de 2
11 no es múltiplo de 2
13 no es múltiplo de 2
15 no es múltiplo de 2
17 no es múltiplo de 2
19 no es múltiplo de 2
21 no es múltiplo de 2
23 no es múltiplo de 2
25 no es múltiplo de 2
27 no es múltiplo de 2
29 no es múltiplo de 2
31 no es múltiplo de 2
33 no es múltiplo de 2
35 no es múltiplo de 2
37 no es múltiplo de 2
39 no es múltiplo de 2
41 no es múltiplo de 2
43 no es múltiplo de 2
45 no es múltiplo de 2
47 no es múltiplo de 2
49 no es múltiplo de 2
51 no es múltiplo de 2
53 no es múltiplo de 2
55 no es múltiplo de 2
57 no es múltiplo de 2
59 no es múltiplo de 2
61 no es múltiplo de 2
63 no es múltiplo de 2
65 no es múltiplo de 2
67 no es múltiplo de 2
69 no es múltiplo de 2
71 no es múltiplo de 2
73 no es múltiplo de 2
75 no es múltiplo de 2
77 no es múltiplo de 2
79 no es múltiplo de 2
81 no es múltiplo de 2
83 no es múltiplo de 2
85 no es múltiplo de 2
87 no es múltipl

In [94]:
for i ∈ 1:10
    if i%2 == 0
        println("Soy $i y soy par")
    else
        println("Soy $i y soy impar")
    end
end

Soy 1 y soy impar
Soy 2 y soy par
Soy 3 y soy impar
Soy 4 y soy par
Soy 5 y soy impar
Soy 6 y soy par
Soy 7 y soy impar
Soy 8 y soy par
Soy 9 y soy impar
Soy 10 y soy par


In [3]:
for i ∈ -3:3
    if i < 0
        println("Soy $i y soy negativo")
    elseif i == 0
        println("Soy $i y soy cero")
    elseif i == 1
        println("Soy $i uno")
    else
        println("Soy $i y soy positivo")
    end
end

Soy -3 y soy negativo
Soy -2 y soy negativo
Soy -1 y soy negativo
Soy 0 y soy cero
Soy 1 uno
Soy 2 y soy positivo
Soy 3 y soy positivo


# While

Existen ocasiones en las que queremos repetir operaciones hasta que cierta condición se cumpla para eso utilizamos el `while`

In [4]:
a = 0.2
b = 10
c = 0
while b > 0
    c += 1
    b = b - a
end
println("Se necesitaron $c pasos para que b fuera menor o igual a 0 (b = $(round(b,2)))")

Se necesitaron 51 pasos para que b fuera menor o igual a 0 (b = -0.2)


In [97]:
a = 0.2
b = 10
c = 0
while b > 0
    c += 1
    b = b - a
end
println("Se necesitaron $c pasos para que b fuera menor o igual a 0 (b = $b)")

Se necesitaron 51 pasos para que b fuera menor o igual a 0 (b = -0.19999999999999796)


In [98]:
a = 0.0625 # 1/16 = 0.0625
b = 10
c = 0
while b > 0
    c += 1
    b = b - a
end
println("Se necesitaron $c pasos para que b fuera menor o igual a 0 (b = $b)")

Se necesitaron 160 pasos para que b fuera menor o igual a 0 (b = 0.0)


<font size="5" color="red"> Por la representación en números flotantes y el número de máquina lo mejor es usar pasos de $\frac{1}{2^n}$ es decir, uno sobre potencias de dos.</font>

# Funciones

Muchas veces queremos repetir tareas y volver a escribir el mismo código cada vez que se quiere utilizar no es lo más óptimo por tiempo y por claridad de lectura.

In [99]:
function mi_factorial(n) # n es la variable a la que le quiero aplicar la función
    if n == 0
        1
    else
        n * mi_factorial(n-1)
    end
end

mi_factorial (generic function with 1 method)

In [100]:
mi_factorial(5)

120

In [101]:
mi_factorial(25)

7034535277573963776

In [102]:
factorial_de_cinco = mi_factorial(5)

120

In [103]:
factorial_de_cinco

120

### Podemos tener de argumento y de respuesta más de una variable, nota que todo lo definido afuera de la función no se guarda en la sesión (scope de una variable)

In [104]:
function multivariable(x1,x2,x3)
    y1 = x1 + x2
    y2 = x2 + x3
    y3 = x1 + x2 + x3
    y1, y2, y3
end

multivariable (generic function with 1 method)

In [105]:
multivariable(1,2,3)

(3,5,6)

In [106]:
y1

LoadError: UndefVarError: y1 not defined

Como mencionamos anteriormente, esa variable no existe pues sólo es posible verla adentro de la función. Afuera no está definida. Pero es posible guardar las variables usando su salida.

In [107]:
y1, y2, y3 = multivariable(1,2,3)

(3,5,6)

In [108]:
y1

3

No tiene que ser el mismo nombre que el de adentro

In [109]:
suma_primeros_dos, suma_segundos_dos, suma_todos = multivariable(1,2,3)

(3,5,6)

In [110]:
suma_primeros_dos

3

In [111]:
y1 == suma_primeros_dos

true

Pero sí tienen que ser el mismo número de argumentos

In [116]:
a1, a2 = multivariable(1,2,3)

(3,5,6)

In [119]:
a1

3

In [118]:
a2

5

In [120]:
a3

LoadError: UndefVarError: a3 not defined

# Comprensión de listas

Podemos hacer arreglos mediante el uso de `for loops`

In [121]:
[i for i ∈ 1:10]

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [122]:
a = [i for i in 1:10]
b = [a[i]^2 for i in eachindex(a)]

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [123]:
a = [i for i in 1:10]
b = [entrada^2 for entrada in a]

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

## Un poco más avanzado --- Iteradores

In [125]:
a = [i for i in 1:10]
b = (entrada^2 for entrada in a)

Base.Generator{Array{Int64,1},##15#16}(#15,[1,2,3,4,5,6,7,8,9,10])

In [127]:
for elemento in b
    println(elemento)
end

1
4
9
16
25
36
49
64
81
100


# Pasemos al ejemplo en REPL

In [19]:
;ls

con root.ipynb
Intro 1.ipynb
Proyecto 1
pruebita.ipynb
