In [ ]:
# A)  Crearemos una funcion para multiplicar una matriz por un vector 

In [2]:
function mat_x_vec(A,v)
    if size(A)[2] == length(v) # creamos una condicion con if ya que si el tamaño de la matriz A es igual a la extension del vector ...el vector resultante sera igual a la extension de del la matriz A 
        vector_resultante = zeros(size(A)[1])
        for renglon in 1:size(A)[1] #creamos un ciclo for donde para cada renglon  en en tamaño de la matriz en el primer renglon la entrada sera igual menor que cero
            entrada=0<
            for columna in 1:size(A)[2] # se crea otro ciclo for donde para cada renglon  en en tamaño de la matriz en el segundo renglon ,la multiplicacion sera igual a la matriz en el que  el renglon y la columna seran multiplicadas por la columna del vector 
                multiplicacion=A[renglon,columna]*v[columna]
                entrada+=multiplicacion
            end
            vector_resultante[renglon] = entrada #la entrada cambiara y sera igual a la multiplicacion y el renglon del vector resultante sera igual a la entrada y se termina el ciclo con end y muestra el resultado y termina con end 
        end
        vector_resultante
    end
end

mat_x_vec (generic function with 1 method)

In [3]:
# Creamos la matriz 
A=[(8,9,17),(5,6,11),(8, 9,10)]

3-element Array{Tuple{Int64,Int64,Int64},1}:
 (8, 9, 17)
 (5, 6, 11)
 (8, 9, 10)

In [4]:
# creamos el vector 
v=[(4,6,7)]

1-element Array{Tuple{Int64,Int64,Int64},1}:
 (4, 6, 7)

In [6]:
#  realizamos el producto de las dos
function mat_x_vec(A,v)

LoadError: syntax: incomplete: premature end of input

In [ ]:
# Crearemos una funcion para multiplicar dos matrices

In [2]:
#Creamos una funcion para calcular el producto de dos matrices
function ProdMat(a,b)
    if (size(a)[2]==size(b)[2])
        for i ∈ 1:size(a)[1]
            k=1
            while k<=size(a)[1]
                p=0
                for j ∈ 1:size(b)[1]
                    A=a[i,j]*b[j,k]
                    p+=A
                    end
                b[i,k]=p
                k+=1
                end
        end
         b
    else
        print("checa las dimenciones")
    end
end
# Comenzamos con un condicional if ya que si el tamaño de las dos matrices es igual con for porque para cada numero i en la extension de la matriz tendremos que k sera igual a 1
# despues con un whileque nos dice que mientras k sea menor igual al tamaño de la primera matriz p sera igual a 0
# con un for porque nos dice que por cada termino en el tamaño de la segunda matriz tendremos que A sera igual la multiplicacion de los terminos tendremos que p sera igual a p mas A y terminams con un end
# tambienm que los terminos de la matriz seran igual a p y k sera igual a k mas 1 y terminamos con un end lo que se anexo y despues otro end
# y por ultimo con un else para agregar que con print nos marque si debemos revisar las dimensiones y terminamos con un end

ProdMat (generic function with 1 method)

In [3]:
# Creamos la matriz
a=[1 5 6;7 6 1;3 8 9;]

3×3 Array{Int64,2}:
 1  5  6
 7  6  1
 3  8  9

In [4]:
# Creamos la aegunda matriz
b=[9 8 7;4 5 6;1 2 3]

3×3 Array{Int64,2}:
 9  8  7
 4  5  6
 1  2  3

In [5]:
# realizamos la operacion
ProdMat(a,b)

3×3 Array{Int64,2}:
   35    45    55
  270   347   424
 2274  2929  3584