In [ ]:
#  A) realizaremos la suma de dos matrices

In [2]:
# crearemos una funcion para calcular la suma de dos matrices
function SumaMat(A,B)
    if size(A)==(2, 2);size(B)==(2, 2) # usamos un if como condicional ya que si el tamaño del vector A es igual a el vector B 
        C=zeros(size(A)) # creamos un arreglo de zaros para la matriz A
        for i ∈ 1:size(A)[1] # creamos un ciclo for que nos dice por cada numero en el tamaño de la matriz A en la primera columna
            for j ∈ 1:size(A)[2] # creamos un ciclo for nuevamente donde  nos dice que por cada otro numero en el tamaño de la matriz en la segunda columna tendremos que b sera igual a la suma de un numero de la matriz A mas un numero de la matriz B  e igual con el otro numero
                b=A[i,j]+B[i,j]
                C[i,j]+=b # tenemos que aqui se suman los numeros de cada matriz y se termina con un end y si no pasa lo anterir le decimos con print que nos marque error y terminaremos el ciclo con un end
            end
        end
        C
    else
        print("error")
    end
end

SumaMat (generic function with 1 method)

In [6]:
# creamos la primera matriz en forma de lista
A = [8 9; 6 5;]

2×2 Array{Int64,2}:
 8  9
 6  5

In [5]:
# creamos la segunda matriz en forma de lista
B = [8 5 ; 9 8;]

2×2 Array{Int64,2}:
 8  5
 9  8

In [7]:
# Realizamos la operacion
SumaMatr2X2(A,B)

2×2 Array{Float64,2}:
 16.0  14.0
 15.0  13.0